"use strict";

function cmdHelp() {
  const text = [
    "SDTK-CODE CLI -- coding process discipline toolkit",
    "",
    "Usage:",
    "  sdtk-code <command> [options]",
    "",
    "Commands:",
    "  start     Create or refresh CODE_WORKFLOW from formal handoff or compatibility inputs",
    "  plan      Refine downstream execution slices inside the approved handoff scope",
    "  build     Record build progress and route the next coding engine step",
    "  verify    Record summarized evidence, write REVIEW_PACKET, and update ordered review gates",
    "  ship      Record final ship or finish decision and emit OPS_HANDOFF on formal closeout",
    "  status    Inspect current workflow lifecycle state and next legal action",
    "  doctor    Diagnose missing or contradictory workflow state (diagnostic only)",
    "  resume    Continue only when resume is machine-safe; otherwise fail closed",
    "  update    Refresh the npm package and optionally re-apply managed project/runtime assets",
    "  init      Initialize SDTK-CODE workspace",
    "  runtime   Manage runtime asset installation (install, uninstall, status)",
    "  agent-team Plan/preview/export/evidence plus bounded docs/governance Markdown execute/author/sleep-execute",
    "  sleep     Sleep Mode: plan/report readiness dry-run (free) + authorize/execute (Pro, entitlement-gated)",
    "",
    "Workflow status:",
    "  Implemented now: start, plan, build, verify, ship, status, doctor, resume",
    "",
    "Package status:",
    "  Public package: sdtk-code-kit",
    "  Check latest published version: npm view sdtk-code-kit version",
    "  Canonical command: sdtk-code",
    "  Real workflow execution still expects upstream SDTK-SPEC artifacts",
    "  Current public workflow surface is live on npm",
    "  CI/tag-publish parity remains follow-up hardening, not a blocker for the current public package line",
    "  Payload stays intentionally narrow and ships runtime assets plus CODE_WORKFLOW_TEMPLATE.md",
    "",
    "Start options:",
    "  --feature-key <KEY>            Feature key in UPPER_SNAKE_CASE (required)",
    "  --lane <feature|bugfix>        Explicit workflow lane (required)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "  --force                        Reinitialize an existing workflow artifact",
    "",
    "Start intake truth:",
    "  Prefers docs/dev/CODE_HANDOFF_[FEATURE_KEY].json when present",
    "  Falls back to FEATURE_IMPL_PLAN + sdtk-spec.config.json only when the formal handoff file is missing",
    "  Feature lane expects formal handoff by default; bugfix may use compatibility fallback when missing",
    "  Invalid or blocked formal handoff stops start and writes a blocked workflow artifact",
    "  FEATURE_IMPL_PLAN remains the upstream /dev implementation-readiness plan; CODE plan only refines execution slices after intake",
    "",
    "Plan options:",
    "  --feature-key <KEY>            Feature key in UPPER_SNAKE_CASE (required)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "  --in-scope <text>              Record an in-scope item (repeatable)",
    "  --out-scope <text>             Record an out-of-scope item (repeatable)",
    "  --slice <text>                 Record a planning slice (repeatable; explicit refinement path for feature lane)",
    "  --use-seeded-candidates        Confirm the seeded feature-lane slice set from the formal handoff",
    "  --assumption <text>            Record a planning assumption (repeatable)",
    "  --risk <text>                  Record a planning risk (repeatable)",
    "  --note <text>                  Record an additional planning note (repeatable)",
    "",
    "Build options:",
    "  --feature-key <KEY>            Feature key in UPPER_SNAKE_CASE (required)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "  --active-slice <text>          Record an active build slice (repeatable)",
    "  --note <text>                  Record a build note (repeatable)",
    "  --debug-note <text>            Record a reactive debug note (repeatable)",
    "  --parallel-reason <text>       Explicit justification for code-parallel in feature lane",
    "  --complete                     Mark the current build pass complete and route to verify",
    "  --blocked                      Mark the current build pass blocked and keep routing on build",
    "",
    "Verify options:",
    "  --feature-key <KEY>            Feature key in UPPER_SNAKE_CASE (required)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "  --evidence <text>              Summarized evidence entry in the form",
    "                                 \"check|summary|pass|docs/dev/evidence/FEATURE_KEY/file.txt\"",
    "                                 (repeatable; at least one required)",
    "  --batch-summary <text>         High-level batch summary for REVIEW_PACKET generation",
    "  --changed-file <text>          Changed-file entry in the form",
    "                                 \"repo/path|rationale\" (repeatable)",
    "  --exclude-file <text>          Exclusion entry in the form",
    "                                 \"repo/path|reason\" (repeatable)",
    "  --truth-sync-target <text>     Truth-sync entry in the form",
    "                                 \"path-or-surface|touched|rationale\"",
    "                                 (status must be touched or untouched; repeatable)",
    "  --commit-include <path>        Repo-relative file to include in the proposed commit boundary",
    "                                 (repeatable)",
    "  --commit-exclude <path>        Repo-relative file to exclude from the proposed commit boundary",
    "                                 (repeatable)",
    "  --caveat <text>                Caveat entry in the form",
    "                                 \"ID|statement|impact|owner\" (repeatable)",
    "  --reviewer-guidance <text>     Additional reviewer guidance line for REVIEW_PACKET",
    "                                 (repeatable)",
    "  --spec-status <pending|pass|partial|fail>",
    "                                 Current spec/compliance review gate status",
    "  --spec-note <text>             Record a spec/compliance review note (repeatable)",
    "  --quality-status <pending|pass|partial|fail>",
    "                                 Current quality review gate status",
    "  --quality-note <text>          Record a quality review note (repeatable)",
    "  --debug-note <text>            Record reactive debug follow-up from verification (repeatable)",
    "  --complete                     Mark verify complete and route to ship",
    "  --blocked                      Keep verify blocked and route back to verification work",
    "",
    "Ship options:",
    "  --feature-key <KEY>            Feature key in UPPER_SNAKE_CASE (required)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "  --decision <ship|finish>       Final decision to record (required)",
    "  --preflight <text>             Preflight entry in the form",
    "                                 \"check|summary|pass|docs/dev/evidence/FEATURE_KEY/file.txt\"",
    "                                 (repeatable; at least one required)",
    "  --follow-up <text>             Record a deferred follow-up item (repeatable)",
    "  --note <text>                  Record a ship/finalization note (repeatable)",
    "  --debug-note <text>            Record reactive debug follow-up from preflight (repeatable)",
    "  --blocked                      Keep ship blocked and route back to code-debug/code-ship",
    "",
    "Ship closeout truth:",
    "  Completed closeout backed by docs/dev/CODE_HANDOFF_[FEATURE_KEY].json writes docs/dev/OPS_HANDOFF_[FEATURE_KEY].json",
    "  Compatibility fallback workflows do not emit a fake OPS handoff without the current formal CODE_HANDOFF",
    "",
    "Status options:",
    "  --feature-key <KEY>            Feature key in UPPER_SNAKE_CASE (required)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "",
    "Doctor options:",
    "  --feature-key <KEY>            Feature key in UPPER_SNAKE_CASE (required)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "  Doctor is diagnostic-only in BK-047-lite and does not auto-repair workflow files.",
    "",
    "Resume options:",
    "  --feature-key <KEY>            Feature key in UPPER_SNAKE_CASE (required)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "  Resume auto-dispatch is currently bounded to machine-safe build transitions only.",
    "  Resume fails closed for plan, verify, and ship because explicit operator inputs are required.",
    "",
    "Init options:",
    "  --runtime <codex|claude>       Runtime adapter (default: codex)",
    "  --runtime-scope <project|user> Install scope (default: project for claude, user for codex)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "  --force                        Overwrite existing files",
    "  --skip-runtime-assets          Skip runtime skill installation",
    "  --skip-skills                  Deprecated alias for --skip-runtime-assets",
    "  --verbose                      Show detailed PowerShell script output",
    "",
    "Runtime subcommands:",
    "  sdtk-code runtime install   --runtime <codex|claude> [--scope <project|user>]",
    "  sdtk-code runtime uninstall --runtime <codex|claude> [--scope <project|user>] [--all]",
    "  sdtk-code runtime status    --runtime <codex|claude> [--project-path <path>]",
    "",
    "Update options:",
    "  --version <latest|x.y.z>    Target published npm package version (default: latest)",
    "  --runtime <codex|claude>    Optional runtime refresh target after npm update",
    "  --scope <project|user>      Runtime asset scope when --runtime is provided",
    "  --project-path <path>       Target project directory for managed file refresh (default: cwd)",
    "  --check-only                Print the planned npm/init/runtime refresh steps without making changes",
    "  --skip-project-files        Skip sdtk-code init --force during update",
    "  --skip-runtime-assets       Skip sdtk-code runtime install --force during update",
    "  --verbose                   Show detailed command output",
    "  Maintainer-root guard: init/update refuse the SDTK maintainer monorepo root as a managed project target.",
    "  Use a consumer project path, or use --skip-project-files when update should avoid project-file refresh.",
    "",
    "Agent-team subcommands:",
    "  sdtk-code agent-team plan      --feature-key <KEY> [--project-path <path>]",
    "  sdtk-code agent-team preview   --feature-key <KEY> [--project-path <path>]",
    "  sdtk-code agent-team export    --feature-key <KEY> --runtime <codex|claude> [--project-path <path>]",
    "  sdtk-code agent-team evidence submit --feature-key <KEY> --role <pm|dev|qa> --evidence-file <path> [--project-path <path>]",
    "  sdtk-code agent-team readiness --feature-key <KEY> [--project-path <path>]",
    "  sdtk-code agent-team report    --feature-key <KEY> [--project-path <path>]",
    "  sdtk-code agent-team execute   --feature-key <KEY> --patch-file <path> [--dry-run|--execute] [--project-path <path>]",
    "  sdtk-code agent-team author    --feature-key <KEY> [--dry-run|--execute] [--project-path <path>]",
    "  sdtk-code agent-team sleep-execute --feature-key <KEY> [--patch-file <path>] [--dry-run|--execute] [--project-path <path>]",
    "  evidence submit validates and stores agent-submitted evidence under .sdtk/agent-team/evidence/<KEY>/",
    "  readiness scores all roles and declares READY_TO_SLEEP or NOT_READY",
    "  report writes morning_report.md from evidence + readiness",
    "  execute is docs/governance Markdown Flow B: dry-run default; --execute requires exact TTY confirmation",
    "  author is attended D-2b: dry-run makes no model call; --execute makes one model call then uses the same bounded harness; no auto-merge",
    "  sleep-execute is attended single-session Phase E Preview: free/MIT; model/API cost is user-provided via your own provider key, not SDTK-hosted; bounded to <=3 author iterations into one worktree for one human review; not unattended autonomy",
    "  READY_TO_SLEEP indicates evidence is present and well-formed — it does NOT verify",
    "  implementation correctness. Human review required before acting on this verdict.",
    "  run is not available in this phase; execute never spawns LLM agents and never auto-merges.",
  "  No .codex/agents or .claude files are written.",
    "",
    "Sleep Mode:",
    "  sdtk-code sleep plan      --feature-key <KEY> [--allowed <glob>]... [--blocked <glob>]... [--scope-file <path>] [--max-actions <n>] [--max-iterations <n>] [--project-path <path>]",
    "  sdtk-code sleep report    --feature-key <KEY> [--project-path <path>]",
    "  sdtk-code sleep authorize --feature-key <KEY> [--max-iterations <n>] [--max-cost-usd <x>] [--ttl-hours <h>] [--project-path <path>]",
    "  sdtk-code sleep execute   --feature-key <KEY> [--session-id <id>] [--project-path <path>]",
    "  plan/report are the free dry-run readiness gate; nothing is executed by them.",
    "  authorize is the attended Pro step: an exact typed TTY confirmation writes a sha256-bound, TTL-limited sleep-authorization artifact (doc-class patches only in v1).",
    "  execute is Pro and entitlement-gated (capability code.sleep.execute): it runs the bounded Phase E session headlessly, ONLY against a valid unexpired authorization, inside the same stop conditions, budgets, and patch guards; editing the plan or scope after authorize invalidates the artifact.",
    "",
    "Runtime options:",
    "  --runtime <codex|claude>   Target runtime (required)",
    "  --scope <project|user>     Install scope (default: project for claude, user for codex)",
    "  --project-path <path>      Target project directory (default: cwd)",
    "  --force                    Overwrite existing managed skills",
    "  --all                      Explicit alias for uninstalling all managed skills",
    "  --verbose                  Show detailed script output",
    "",
    "Scope behavior:",
    "  claude/project  -> <project>/.claude/skills",
    "  claude/user     -> ~/.claude/skills",
    "  codex/project   -> <project>/.codex/skills",
    "  codex/user      -> $CODEX_HOME/skills or ~/.codex/skills",
    "  Note: Codex project scope is supported only via the explicit local CODEX_HOME=<project>/.codex contract.",
    "  Note: This CLI does not claim native .codex/skills auto-discovery.",
    "",
    "Uninstall behavior:",
    "  runtime uninstall removes only SDTK-CODE-managed skill folders for the selected runtime/scope.",
    "  It does not delete parent runtime roots such as .claude/, .claude/skills/, $CODEX_HOME/, or $CODEX_HOME/skills/.",
    "  npm uninstall -g sdtk-code-kit removes the CLI package only. Runtime assets remain until runtime uninstall or manual cleanup.",
    "",
    "Skill naming:",
    "  Claude installs: code-*",
    "  Codex installs:  sdtk-code-*",
    "",
    "Global options:",
    "  -h, --help      Show this help",
    "  -v, --version   Show version",
    "",
    "Exit codes:",
    "  0  Success",
    "  1  Validation or user error",
    "  2  Dependency error",
    "  3  Integrity error",
    "  4  Unexpected internal error",
    "",
    "Examples:",
    "  sdtk-code start --feature-key ORDER_MGMT --lane feature --project-path ./my-project",
    "  sdtk-code start --feature-key LOGIN_FIX --lane bugfix --project-path ./my-project",
    "  sdtk-code plan --feature-key ORDER_MGMT --use-seeded-candidates",
    "  sdtk-code plan --feature-key ORDER_MGMT --slice \"API contract updates\" --slice \"UI register flow\"",
    "  sdtk-code plan --feature-key LOGIN_FIX --note \"Bugfix planning override\"",
    "  sdtk-code build --feature-key ORDER_MGMT --active-slice \"API contract updates\" --parallel-reason \"Backend and UI are isolated\"",
    "  sdtk-code build --feature-key LOGIN_FIX --debug-note \"Failure reproduced in session timeout flow\" --complete",
    "  sdtk-code verify --feature-key ORDER_MGMT --evidence \"pytest -q|Regression suite passed|pass|docs/dev/evidence/ORDER_MGMT/pytest.txt\" --spec-status pass --quality-status partial",
    "  sdtk-code verify --feature-key LOGIN_FIX --evidence \"npm test|Bugfix regression passes|pass|docs/dev/evidence/LOGIN_FIX/regression.txt\" --spec-status pass --quality-status pass --complete",
    "  sdtk-code ship --feature-key ORDER_MGMT --decision ship --preflight \"npm pack --dry-run|Package smoke passed|pass|docs/dev/evidence/ORDER_MGMT/pack.txt\" --preflight \"release checklist|Operator handoff reviewed|pass|docs/dev/evidence/ORDER_MGMT/release-checklist.txt\" --follow-up \"Monitor first-release support tickets\"",
    "  sdtk-code ship --feature-key LOGIN_FIX --decision finish --preflight \"git diff --check|No whitespace issues remain|pass|docs/dev/evidence/LOGIN_FIX/diff-check.txt\"",
    "  sdtk-code status --feature-key ORDER_MGMT --project-path ./my-project",
    "  sdtk-code doctor --feature-key ORDER_MGMT --project-path ./my-project",
    "  sdtk-code resume --feature-key ORDER_MGMT --project-path ./my-project",
    "  sdtk-code init",
    "  sdtk-code init --runtime codex --runtime-scope project --project-path ./my-project",
    "  sdtk-code init --runtime claude --project-path ./my-project",
    "  sdtk-code update --check-only",
    "  sdtk-code update --runtime claude --project-path ./my-project",
    "  sdtk-code update --version 1.2.3 --runtime codex --scope user --skip-project-files",
    "  sdtk-code init --runtime claude --runtime-scope user",
    "  sdtk-code runtime install --runtime claude --scope project --project-path ./my-project",
    "  sdtk-code runtime install --runtime codex --scope user",
    "  sdtk-code runtime install --runtime codex --scope project --project-path ./my-project",
    "  sdtk-code runtime status --runtime claude --project-path ./my-project",
    "  sdtk-code runtime uninstall --runtime codex --all",
    "  npm uninstall -g sdtk-code-kit",
    "",
    "Next steps after init:",
    "  1. Review and customize sdtk-spec.config.json for your project.",
    "  2. Create or refresh CODE_WORKFLOW with sdtk-code start once the upstream SDTK-SPEC handoff exists.",
    "     Preferred input: CODE_HANDOFF_[FEATURE_KEY].json; compatibility fallback is bounded to missing-handoff cases.",
    "  3. For feature work, either confirm seeded handoff slices with --use-seeded-candidates or refine them with explicit --slice entries.",
    "  4. Record build progress with sdtk-code build while execution is in motion.",
    "  5. Use sdtk-code status for a fast lifecycle snapshot before resuming interrupted work.",
    "  6. Use sdtk-code doctor when state looks contradictory or blocks unexpectedly (diagnostic only).",
    "  7. Use sdtk-code resume only when a machine-safe resume path is available.",
    "  8. Capture summarized evidence and review gates with sdtk-code verify before closure.",
    "     Verify also emits docs/dev/REVIEW_PACKET_[FEATURE_KEY].md for downstream QA/controller review.",
    "  9. Record final ship or finish decision with sdtk-code ship; completed formal closeout writes OPS_HANDOFF for DEV-Run intake.",
    "  10. Use raw code-* skills directly when you intentionally choose expert mode.",
  ];

  console.log(text.join("\n"));
  return 0;
}

module.exports = {
  cmdHelp,
};
