"use strict";

function cmdHelp() {
  const text = [
    "SDTK-OPS CLI -- skill-driven operations discipline toolkit",
    "",
    "Usage:",
    "  sdtk-ops <command> [options]",
    "",
    "Commands:",
    "  init      Initialize SDTK-OPS files in a project",
    "  runtime   Manage runtime asset installation (install, uninstall, status)",
    "  update    Refresh the npm package and optionally re-apply managed project/runtime assets",
    "  help      Show this help message",
    "",
    "Current supported surface:",
    "  Supported now: help, init, runtime install|status|uninstall",
    "  Not supported: generate",
    "  Package scope: public npm package",
    "",
    "DEV-Run intake:",
    "  Canonical intake artifact: docs/dev/OPS_HANDOFF_[FEATURE_KEY].json",
    "  READY_FOR_SDTK_OPS: start from suggested_next_ops_path or confirm it with ops-discover.",
    "  BLOCKED_FOR_SDTK_OPS: inspect blockers and evidence refs, but do not treat it as normal ready-path execution.",
    "  SDTK-OPS consumes the frozen handoff contract and does not redefine the schema.",
    "",
    "Workflow entry:",
    "  After init, choose a journey directly if the goal is clear.",
    "  Canonical journeys: deployment, incident, monitoring, backup/recovery.",
    "  If the correct path is unclear, start with the ops-discover skill.",
    "  ops-parallel remains valid only for independent slices; if collab/subagent dispatch is unavailable in the active runtime, keep the same split but execute sequentially.",
    "  Close every journey with ops-verify before declaring work complete.",
    "",
    "Runtime support:",
    "  Claude: project + user scope",
    "  Codex:  default user scope plus bounded project scope via <project>/.codex",
    "  Codex project scope requires the explicit local CODEX_HOME=<project>/.codex contract",
    "  Native .codex/skills auto-discovery is not claimed",
    "",
    "Runtime commands:",
    "  sdtk-ops runtime install --runtime <codex|claude> [--scope <project|user>] [--project-path <path>]",
    "  sdtk-ops runtime uninstall --runtime <codex|claude> [--scope <project|user>] [--all] [--project-path <path>]",
    "  sdtk-ops runtime status --runtime <codex|claude> [--project-path <path>]",
    "",
    "Update options:",
    "  --version <latest|x.y.z>    Target published npm package version (default: latest)",
    "  --runtime <codex|claude>    Optional runtime refresh target after npm update",
    "  --scope <project|user>      Runtime asset scope when --runtime is provided",
    "  --project-path <path>       Target project directory for managed file refresh (default: cwd)",
    "  --check-only                Print the planned npm/init/runtime refresh steps without making changes",
    "  --skip-project-files        Skip sdtk-ops init --force during update",
    "  --skip-runtime-assets       Skip sdtk-ops runtime install --force during update",
    "  --verbose                   Show detailed command output",
    "  Maintainer-root guard: init/update refuse the SDTK maintainer monorepo root as a managed project target.",
    "  Use a consumer project path, or use --skip-project-files when update should avoid project-file refresh.",
    "",
    "Uninstall behavior:",
    "  runtime uninstall removes only SDTK-OPS-managed skill folders for the selected runtime/scope.",
    "  It does not delete parent runtime roots such as .claude/, .claude/skills/, $CODEX_HOME/, or $CODEX_HOME/skills/.",
    "  npm uninstall -g sdtk-ops-kit removes the CLI package only. Runtime assets remain until runtime uninstall or manual cleanup.",
    "",
    "Global options:",
    "  -h, --help      Show this help",
    "  -v, --version   Show version",
    "",
    "Examples:",
    "  sdtk-ops --help",
    "  sdtk-ops --version",
    "  sdtk-ops init --runtime claude --project-path ./my-project",
    "  sdtk-ops update --check-only",
    "  sdtk-ops update --runtime claude --project-path ./my-project",
    "  sdtk-ops update --version 1.2.3 --runtime codex --scope user --skip-project-files",
    "  sdtk-ops init --runtime codex --runtime-scope project --project-path ./my-project",
    "  sdtk-ops runtime install --runtime claude --scope project --project-path ./my-project",
    "  sdtk-ops runtime install --runtime codex --scope project --project-path ./my-project",
    "  # Journey routing after init:",
    "  # deployment -> ops-plan -> ops-infra-plan -> ops-container -> ops-ci-cd -> ops-deploy -> ops-monitor -> ops-verify",
    "  # incident   -> ops-incident -> ops-debug -> ops-monitor -> ops-verify",
    "  # monitoring -> ops-plan -> ops-monitor -> ops-verify",
    "  # recovery   -> ops-plan -> ops-backup -> ops-verify",
    "  sdtk-ops runtime status --runtime codex",
    "  sdtk-ops runtime uninstall --runtime codex --scope user",
    "  npm uninstall -g sdtk-ops-kit",
  ];

  console.log(text.join("\n"));
  return 0;
}

module.exports = { cmdHelp };
