"use strict";

function cmdHelp() {
  const text = [
    "SDTK-SPEC CLI -- deterministic documentation toolkit",
    "",
    "Usage:",
    "  sdtk-spec <command> [options]",
    "",
    "Commands:",
    "  init          Initialize SDTK-SPEC workspace (runtime adapter + config)",
    "  atlas         Build and browse the free local Atlas compatibility graph",
    "  runtime       Manage runtime asset installation (install, uninstall, status)",
    "  update        Refresh the npm package and optionally re-apply managed project/runtime assets",
    "  generate      Create the standard 17-file feature scaffold from templates",
    "  analyze       Preserve requirement source, bootstrap scaffold, and create an agent task packet",
    "  config        Project config helpers: apply a stack profile, check for unfilled placeholders",
    "",
    "Config subcommands:",
    "  sdtk-spec config apply-profile <name> [--project-path <path>] [--json]",
    "  sdtk-spec config check [--project-path <path>] [--json]",
    "  apply-profile merges a profile from sdtk-spec.config.profiles.example.json into",
    "  sdtk-spec.config.json (orchestration/stack/commands), preserving docs, schemaVersion,",
    "  and stack.detection. check exits 1 while UPDATE_ME placeholders remain — wire it into gates.",
    "",
    "Init options:",
    "  --runtime <codex|claude>       Runtime adapter (default: codex)",
    "  --runtime-scope <project|user> Install scope (default: project for claude, user for codex)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "  --force                        Overwrite existing files",
    "  --skip-runtime-assets          Skip runtime asset installation",
    "  --skip-skills                  (deprecated, use --skip-runtime-assets)",
    "  --verbose                      Show detailed PowerShell script output",
    "",
    "Runtime subcommands:",
    "  sdtk-spec runtime install   --runtime <codex|claude> [--scope <project|user>]",
    "  sdtk-spec runtime uninstall --runtime <codex|claude> [--scope <project|user>] [--all]",
    "  sdtk-spec runtime status    --runtime <codex|claude>",
    "",
    "Update options:",
    "  --version <latest|x.y.z>    Target published npm package version (default: latest)",
    "  --runtime <codex|claude>    Optional runtime refresh target after npm update",
    "  --scope <project|user>      Runtime asset scope when --runtime is provided",
    "  --project-path <path>       Target project directory for managed file refresh (default: cwd)",
    "  --check-only                Print the planned npm/init refresh steps without making changes",
    "  --skip-project-files        Skip sdtk-spec init --force during update",
    "  --skip-runtime-assets       Skip runtime asset refresh during update",
    "  --verbose                   Show detailed command output",
    "  Maintainer-root guard: init/update refuse the SDTK maintainer monorepo root as a managed project target.",
    "  Use a consumer project path, or use --skip-project-files when update should avoid project-file refresh.",
    "",
    "Runtime options:",
    "  --runtime <codex|claude>   Target runtime (required)",
    "  --scope <project|user>     Install scope (default: project for claude, user for codex)",
    "  --project-path <path>      Target project directory (default: cwd)",
    "  --force                    Overwrite existing skills",
    "  --all                      Uninstall all managed skills",
    "  --verbose                  Show detailed script output",
    "",
    "Scope behavior:",
    "  project  Claude installs to <project>/.claude/skills and Codex installs to <project>/.codex/skills",
    "  user     Skills are installed in the runtime home (~/.claude/skills/ or $CODEX_HOME/skills / ~/.codex/skills)",
    "  Note: Codex project scope is supported only via the explicit local CODEX_HOME=<project>/.codex contract.",
    "  Note: This CLI does not claim native .codex/skills auto-discovery.",
    "",
    "Uninstall behavior:",
    "  runtime uninstall removes only SDTK-managed skill folders for the selected runtime/scope.",
    "  It does not delete parent runtime roots such as .claude/, .claude/skills/, $CODEX_HOME/, or $CODEX_HOME/skills/.",
    "  npm uninstall -g sdtk-spec-kit removes the CLI package only. Runtime assets remain until runtime uninstall or manual cleanup.",
    "",
    "Generate options:",
    "  --key <KEY>                Identifier for what you are scaffolding, UPPER_SNAKE_CASE (required)",
    "                            Use a product/MVP (e.g. SHOPEASE) or a single feature (e.g. ORDER_TRACKING)",
    "  --name \"<text>\"           Human-readable name, e.g. \"ShopEase MVP\" (required)",
    "  --feature-key / --feature-name   Backward-compatible aliases of --key / --name",
    "  --project-path <path>      Target project directory (default: cwd)",
    "  --force                    Overwrite existing files",
    "  --validate-only            Validate templates without writing files",
    "  --verbose                  Show detailed PowerShell script output",
    "",
    "Analyze options:",
    "  --source <file>            Customer requirement Markdown/text file (required)",
    "  --key <KEY>                Identifier, UPPER_SNAKE_CASE (required; alias: --feature-key)",
    "  --name \"<text>\"           Human-readable name (required; alias: --feature-name)",
    "  --project-path <path>      Target project directory (default: cwd)",
    "  --force                    Overwrite managed analysis artifacts",
    "  --json                     Print result summary as JSON",
    "",
    "Atlas subcommands (free compatibility path; delegated to sdtk-wiki):",
    "  sdtk-spec atlas init     Initialize the graph workspace and run the first build (opens viewer)",
    "  sdtk-spec atlas build    Rebuild the local document graph from project markdown",
    "  sdtk-spec atlas open     Open the last successful build in a local browser",
    "  sdtk-spec atlas watch    Watch for markdown changes and rebuild automatically",
    "  sdtk-spec atlas status   Show initialization state and last build summary",
    "",
    "Project subcommands:",
    "  sdtk-spec project promote  Publish reviewed staged docs into /docs/ for sdtk-wiki (free; dry-run by default)",
    "",
    "Atlas options:",
    "  Every flag is forwarded verbatim to sdtk-wiki, which owns the option surface:",
    "  --project-path, --output-dir, --scan-root (repeatable), --verbose, --host, --port,",
    "  --no-open; init also accepts --force and --no-build.",
    "  Run 'sdtk-wiki atlas <subcommand> --help' for the authoritative list.",
    "",
    "Atlas notes:",
    "  - Atlas scans markdown files and builds a local document graph and static viewer.",
    "  - sdtk-spec atlas is the R1 compatibility namespace; it delegates to sdtk-wiki, the canonical builder.",
    "  - The builder is pure Node: no interpreter or extra runtime is required.",
    "  - Requires sdtk-wiki-kit (bundled with the sdtk-kit suite). Without it, atlas exits 2 with install steps.",
    "  - Graph output defaults to <project>/.sdtk/wiki/graph/; a legacy <project>/.sdtk/atlas/ is never auto-deleted.",
    "  - The old SPEC ask command path is not supported; native Ask is sdtk-wiki ask with capability wiki.ask.",
    "  - Viewer server binds to 127.0.0.1 by default (loopback only).",
    "",
    "Project promote options (free):",
    "  --project-path <path>    Target project directory (default: cwd)",
    "  --output-dir <path>      Foundation read path (default: <project>/.sdtk/project)",
    "  --apply                  Perform the copy (default is a dry-run plan only)",
    "  --force                  Overwrite existing live docs (default: skip existing)",
    "  --json                   Print the promote plan/result as JSON",
    "",
    "Project promote notes:",
    "  - project promote is free; it publishes reviewed staged docs into <project>/docs/.",
    "  - Default is a dry-run that prints the plan and writes nothing; add --apply to publish.",
    "  - Existing live docs are skipped unless --force is given (human-review-first).",
    "  - After promote, run 'sdtk-wiki atlas build' to index the docs into the knowledge graph.",
    "",
    "Generate behavior:",
    "  The generate command creates the standard 17-file scaffold with TBD placeholders.",
    "  Scaffolds define document structure for each SDLC phase.",
    "  Content is filled in by agents or manually (PM -> BA -> ARCH -> DEV -> QA).",
    "  Output is written to docs/ subdirectories under the project path.",
    "",
    "Analyze behavior:",
    "  The analyze command preserves a requirement source under .sdtk/spec/requirements/.",
    "  It bootstraps the standard 17-file scaffold when missing by reusing generate behavior.",
    "  It creates .sdtk/spec/tasks/<KEY>/ task packets for PM/BA/ARCH/DEV/QA agent analysis.",
    "  It reports likely mojibake/encoding risk and source hash traceability.",
    "  It does not fully understand arbitrary requirements by itself.",
    "  PM/BA/ARCH agents complete source-backed analysis inside the generated artifacts.",
    "  It does not modify the source project and does not create .sdtk/atlas.",
    "",
    "Global options:",
    "  -h, --help                 Show this help",
    "  -v, --version              Show version",
    "",
    "Exit codes:",
    "  0  Success",
    "  1  Validation or user error",
    "  2  Dependency error (e.g., PowerShell not found)",
    "  3  Integrity error (payload hash mismatch)",
    "  4  Unexpected internal error",
    "",
    "Environment variables:",
    "",
    "Examples:",
    "  sdtk-spec atlas init --project-path ./my-project",
    "  sdtk-spec atlas init --project-path ./my-project --no-open",
    "  sdtk-spec atlas build --project-path ./my-project --verbose",
    "  sdtk-spec atlas open --project-path ./my-project --port 9000",
    "  sdtk-spec atlas open --project-path ./my-project --no-open",
    "  sdtk-spec atlas watch --project-path ./my-project",
    "  sdtk-spec atlas status --project-path ./my-project",
    "  sdtk-spec init --runtime codex",
    "  sdtk-spec init --runtime codex --runtime-scope project --project-path ./my-project",
    "  sdtk-spec init --runtime claude --project-path ./my-project",
    "  sdtk-spec update --check-only",
    "  sdtk-spec update --runtime claude --project-path ./my-project",
    "  sdtk-spec update --version 1.2.3 --runtime codex --scope user",
    '  sdtk-spec generate --key SHOPEASE --name "ShopEase MVP"',
    "  sdtk-spec generate --key ORDER_TRACKING --name \"Order Tracking\" --validate-only",
    "  sdtk-spec analyze --source ./requirements.md --key SHOPEASE --name \"ShopEase MVP\"",
    "  sdtk-spec init --runtime claude --runtime-scope user",
    "  sdtk-spec runtime install --runtime claude --scope project",
    "  sdtk-spec runtime install --runtime codex --scope user",
    "  sdtk-spec runtime install --runtime codex --scope project --project-path ./my-project",
    "  sdtk-spec runtime status --runtime claude",
    "  sdtk-spec runtime uninstall --runtime claude --scope project --all",
    "  sdtk-spec project promote --project-path ./my-project",
    "  sdtk-spec project promote --project-path ./my-project --apply",
    "  sdtk-spec project promote --project-path ./my-project --apply --force",
    "  sdtk-spec project promote --project-path ./my-project --json",
    "",
  ];
  console.log(text.join("\n"));
  return 0;
}

module.exports = {
  cmdHelp,
};
