"use strict";

function cmdHelp() {
  const text = [
    "SDTK-SPEC CLI -- deterministic documentation toolkit",
    "",
    "Usage:",
    "  sdtk-spec <command> [options]",
    "",
    "Commands:",
    "  init          Initialize SDTK-SPEC workspace (runtime adapter + config)",
    "  atlas         Build and browse a local document graph for your project",
    "  runtime       Manage runtime asset installation (install, uninstall, status)",
    "  update        Refresh the npm package and optionally re-apply managed project/runtime assets",
    "  generate      Scaffold feature documentation from templates (17 files)",
    "",
    "Init options:",
    "  --runtime <codex|claude>       Runtime adapter (default: codex)",
    "  --runtime-scope <project|user> Install scope (default: project for claude, user for codex)",
    "  --project-path <path>          Target project directory (default: cwd)",
    "  --force                        Overwrite existing files",
    "  --skip-runtime-assets          Skip runtime asset installation",
    "  --skip-skills                  (deprecated, use --skip-runtime-assets)",
    "  --verbose                      Show detailed PowerShell script output",
    "",
    "Runtime subcommands:",
    "  sdtk-spec runtime install   --runtime <codex|claude> [--scope <project|user>]",
    "  sdtk-spec runtime uninstall --runtime <codex|claude> [--scope <project|user>] [--all]",
    "  sdtk-spec runtime status    --runtime <codex|claude>",
    "",
    "Update options:",
    "  --version <latest|x.y.z>    Target published npm package version (default: latest)",
    "  --runtime <codex|claude>    Optional runtime refresh target after npm update",
    "  --scope <project|user>      Runtime asset scope when --runtime is provided",
    "  --project-path <path>       Target project directory for managed file refresh (default: cwd)",
    "  --check-only                Print the planned npm/init refresh steps without making changes",
    "  --skip-project-files        Skip sdtk-spec init --force during update",
    "  --skip-runtime-assets       Skip runtime asset refresh during update",
    "  --verbose                   Show detailed command output",
    "  Maintainer-root guard: init/update refuse the SDTK maintainer monorepo root as a managed project target.",
    "  Use a consumer project path, or use --skip-project-files when update should avoid project-file refresh.",
    "",
    "Runtime options:",
    "  --runtime <codex|claude>   Target runtime (required)",
    "  --scope <project|user>     Install scope (default: project for claude, user for codex)",
    "  --project-path <path>      Target project directory (default: cwd)",
    "  --force                    Overwrite existing skills",
    "  --all                      Uninstall all managed skills",
    "  --verbose                  Show detailed script output",
    "",
    "Scope behavior:",
    "  project  Claude installs to <project>/.claude/skills and Codex installs to <project>/.codex/skills",
    "  user     Skills are installed in the runtime home (~/.claude/skills/ or $CODEX_HOME/skills / ~/.codex/skills)",
    "  Note: Codex project scope is supported only via the explicit local CODEX_HOME=<project>/.codex contract.",
    "  Note: This CLI does not claim native .codex/skills auto-discovery.",
    "",
    "Uninstall behavior:",
    "  runtime uninstall removes only SDTK-managed skill folders for the selected runtime/scope.",
    "  It does not delete parent runtime roots such as .claude/, .claude/skills/, $CODEX_HOME/, or $CODEX_HOME/skills/.",
    "  npm uninstall -g sdtk-spec-kit removes the CLI package only. Runtime assets remain until runtime uninstall or manual cleanup.",
    "",
  console.log(text.join("\n"));
  return 0;
}

module.exports = {
  cmdHelp,
};
